### ISSUE TITLE
TRC task not checking for error code on receipt

### ISSUE THREAD

**Issue by joequant** [Polygant/OpenCEX-backend#139]
The TRC withdrawal logic is not checking for errors on the receipt.  The logic in withdraw_trc20 and withdraw_trx is

    withdrawal_request.state = WR_PENDING
    withdrawal_request.txid = txid
    withdrawal_request.our_fee_amount = token.get_amount_from_base_denomination(withdrawal_fee_sun)
    withdrawal_request.save(update_fields=['state', 'txid', 'updated', 'our_fee_amount'])
    receipt = res.wait()
    log.info(receipt)
    log.info('%s withdrawal TX %s sent', currency, txid)

However if case of transaction 

https://tronscan.org/#/transaction/9e41a0e89c55968311f11ec2c84760b72d5f96256f320e7ab15433094a86bb34

There was a txid but the receipt had failed.  This resulted in a stuck transaction which I was able to reside by going into the 
manager

**Comment by joequant** [comment]
Also one obvious fix would be to check for a failed condition and then reset the state to failed.  However, there is a big possibility of race conditions and security issues and so I would leave it to someone else propose a fix.

**Comment by GreemDark** [comment]
fixed #206
