### ISSUE TITLE
TRX limits should be tweaked 

### ISSUE THREAD

**Issue by joequant** [Polygant/OpenCEX-backend#140]
The withdrawal will fail if the amount of trx in the hot wallet goes below 3 trx.  However, the current price of TRX appears to be about 13 TRX which means that the hot wallet could run out of gas.

Also the min TRX fee is set at 100, which results in about 7 USD being transferred to depositor wallets.  We reduced the amount to 30 TRX and seem to have good results

**Comment by GreemDark** [comment]
pr was accepted
https://github.com/Polygant/OpenCEX-backend/pull/138
